<?php
declare(strict_types=1);

namespace App\Test\TestCase\Model\Table;

use App\Model\Table\LearningResourcesTable;
use Cake\Core\Configure;
use Cake\TestSuite\TestCase;

class LearningResourcesTableTest extends TestCase
{
    protected array $fixtures = [
        'app.LearningResources',
        'app.Classes',
        'app.Teachers',
    ];

    private LearningResourcesTable $LearningResources;

    protected function setUp(): void
    {
        parent::setUp();
        $config = $this->getTableLocator()->exists('LearningResources') ? [] : ['className' => LearningResourcesTable::class];
        $this->LearningResources = $this->getTableLocator()->get('LearningResources', $config);
    }

    public function testResourceUrlRejectsJavascriptScheme(): void
    {
        $resource = $this->LearningResources->newEntity([
            'class_id' => 1,
            'resource_name' => 'Bad scheme',
            'resource_type' => 'link',
            'resource_url' => 'javascript:alert(1)',
            'resource_status' => 'active',
        ]);

        $this->assertNotEmpty($resource->getErrors()['resource_url'] ?? []);
    }

    public function testResourceUrlRejectsDataScheme(): void
    {
        $resource = $this->LearningResources->newEntity([
            'class_id' => 1,
            'resource_name' => 'Bad data scheme',
            'resource_type' => 'link',
            'resource_url' => 'data:text/html;base64,PHNjcmlwdD4=',
            'resource_status' => 'active',
        ]);

        $this->assertNotEmpty($resource->getErrors()['resource_url'] ?? []);
    }

    public function testDatabaseAssignsResourceIdOnInsert(): void
    {
        $resource = $this->LearningResources->newEntity([
            'class_id' => 2,
            'resource_name' => 'Auto resource id',
            'resource_type' => 'document',
            'resource_url' => 'https://example.com/resources/auto-resource-id',
            'resource_description' => 'Generated by DB',
            'uploaded_by_teacher_id' => 2,
            'resource_status' => 'active',
        ], [
            'accessibleFields' => [
                'uploaded_by_teacher_id' => true,
                'resource_status' => true,
            ],
        ]);

        $this->LearningResources->saveOrFail($resource);

        $this->assertNotEmpty($resource->resource_id);
        $this->assertGreaterThan(1, (int)$resource->resource_id);
        $this->assertNotEmpty($resource->uploaded_at);
    }

    public function testLegacyPublicUploadPathRemainsValidForExistingResources(): void
    {
        Configure::write('Uploads.resources_url_prefix', '/resources');

        $resource = $this->LearningResources->newEntity([
            'class_id' => 1,
            'resource_name' => 'Legacy upload path',
            'resource_type' => 'document',
            'file_path' => 'uploads/resources/legacy-guide.pdf',
            'resource_status' => 'active',
        ]);

        $this->assertEmpty($resource->getErrors()['file_path'] ?? []);

        Configure::delete('Uploads.resources_url_prefix');
    }
}
